import { expect } from '../../../test-setup';

import { simplifyHarRequestForSnippetExport } from '../../../../src/model/ui/snippet-export-sanitization';

describe('snippet-export-sanitization', () => {
    it('drops auto-generated headers, drops cookies, and keeps everything else', () => {
        const sanitized = simplifyHarRequestForSnippetExport({
            method: 'POST',
            url: 'https://example.com/path',
            httpVersion: 'HTTP/2.0',
            headers: [
                { name: ':authority', value: 'example.com' },
                { name: 'Content-Length', value: '6' },
                { name: 'Content-Encoding', value: 'gzip' },
                { name: 'Connection', value: 'keep-alive' },
                { name: 'X-Custom-Header', value: 'keep-me' }
            ],
            queryString: [
                { name: 'q', value: '1' }
            ],
            cookies: [
                { name: 'session', value: 'secret' }
            ],
            headersSize: -1,
            bodySize: 6,
            postData: {
                mimeType: 'application/x-www-form-urlencoded',
                text: 'keep=1'
            }
        });

        expect(sanitized.headers).to.deep.equal([
            // Content-length, content-encoding & pseudo-headers are dropped, as
            // they're regenerated by each snippet's HTTP client itself:
            { name: 'Connection', value: 'keep-alive' },
            { name: 'X-Custom-Header', value: 'keep-me' }
        ]);
        expect(sanitized.queryString).to.deep.equal([
            { name: 'q', value: '1' }
        ]);
        expect(sanitized.cookies).to.deep.equal([]); // Already included in the headers
        expect(sanitized.postData).to.deep.equal({
            mimeType: 'application/x-www-form-urlencoded',
            text: 'keep=1'
        });
    });
});
